### PR TITLE
Simple tests reporting on the console

### PR DESCRIPTION
**Pull request by philn**
With this patch applied the tests results JSON data is parsed and some basic informations are reported on the console.

### CODE REVIEW

**Comment by tdedecko** [comment]
I'm not sure why we want to output this information to the console. I personally don't want to flood the console with this information unless it is directly useful. Can you clarify the intention behind this change.

**Comment by tdedecko** [comment]
Please read https://github.com/youtube/js_mse_eme/blob/master/CONTRIBUTING for information on contributing.

**Comment by philn** [comment]
The console is already flooded with XHR logs :)
Anyway, the use-case I have for this change is to run the tests on a remote device to which I don't have visual access to the display. If you don't want this upstream it's also fine with me to reject this pull request, I would understand.

I think Igalia already signed the CLA.

**Comment by tdedecko** [comment]
Yes, it is... :) I have some plans to fix logging in the test suite. It is kind of a disaster right now.
Just found the CLA signed by Igalia.

If the console output is useful for you then I'm sure it will be useful for others. I'll take a look at the change.

Thanks.

**Comment by philn** [comment]
Thom, I updated the patch. Not sure Github sends notifications in that case :)

**Comment by tdedecko** [comment]
I'm working on incorporating some of the ideas presented in this change. I'm not going to merge this pull request since the changes I'm making are not compatible.

**Comment by philn** [comment]
Looking forward.....

**Pull request closed without merging**
