### PR TITLE
Changes related to 2015 tests.

### PR DESCRIPTION
**Pull request by mtheriault**
1-
In the onLoad method of EMEHandler the session variable is used as the session object with MediaKeys or as a session id in the case of 0.1b.
When binding the method we only pass it as id so the session.update call will fail unless we pass the proper object. The patch fixes that.

2-
If you have available both v0.1b and the OO APIs at the same time, setupBaseEmeTest will detect the second and as we fixed previously, we will be sending the session object instead of the necessary session id.
The test could succeed with a V0.1b only browser, but not with one supporting both, specially after the fix for session object.

3-
encryptedMediaPortability.js is now unique to each test suite.
Fixed an issue regarding pre-fixing in 2015 if browser supports v0.1b and the OO APIs.

### CODE REVIEW

**Comment by franckchristin** [comment]
Hi Thom,
I hope you will have time to have a look about this pull request. This blocked to our certification.

Thanks
Franck

**Comment by tdedecko** [comment]
I agree that the EME tests on 2015 need to migrate to OO API.

On the large scale view, I would like to have disparate versions of the EME tests for specific versions of the spec. Previous commits on my part were working on decoupling the EME tests from the MSE tests. The last step is to branch them into their respective versions. It would be great for you to contribute to this effort.

I'm going to close this pull request since it can't be merged in the current state and since we need to separate the 0.1b and the OO versions of the API. I do support a pull request that will work towards this.

**Comment by mtheriault** [comment]
When do you expect your change to separate the 0.1b and the OO versions to be ready?
If it's shortly then I won't bother sending an updated version of this pull request before the changes.

**Comment by tdedecko** [comment]
I don't have a time estimate right now.

**Pull request closed without merging**
