### PR TITLE
Add Web Audio API .createMediaElementSource tests.

### PR DESCRIPTION
**Pull request by kirbysayshi**
Many browsers can playback EME/MSE, but fail when an
MediaElementSourceAudioNode is created from the `<audio>`/`<video>` tag
using the Web Audio API. These tests attempt to show which fail. I'd
like to include a test for actually ensuring audio samples come through
after the MediaElementSourceAudioNode is successfully created, but not
all of the current test media have audio streams.

I tried to match the source style of the existing suite as much as possible, but if there are stylistic or functional changes you would like, please let me know! This suite has proved immensely helpful. If this PR is merged, I would like to file some Bugzilla bugs for FF, as it currently doesn't support MediaElementSourceAudioNode when the source element is EME-powered.

@calvaris @tdedecko Hopefully you're the ones to look at this? Not sure if this repo even accepts external PRs.

### CODE REVIEW

**Comment by tdedecko** [comment]
Thanks for the contribution. I'll have to look into this some more. Not sure yet, if this is an appropriate place for these tests.

In the mean time please make sure to sign the Contributor License Agreement. There is more information in the CONTRIBUTING file.

**Comment by kirbysayshi** [comment]
Thanks for the response! I've previously signed the CLA using drewp@spotify.com (on the commit).

**Comment by tdedecko** [comment]
It would be great to have this contribution.

This would be better as part of the tip tests since it isn't part of our 2017 requirements. This would get rolled into the next version. Please move the tests to tip.

It might be worthwhile to have a test suite that is focused on WebAudio specifically similar to WebGL. I would be happy to reformat the tests to make that change or if you have the time that would be great.

Thanks again for contributing!

**Comment by kirbysayshi** [comment]
@tdedecko Oh sorry, I didn't realize the intended 2017/tip structure! I've moved my changes to tip!

If you feel up to reformatting to a WebAudio-based test I think that would be best. I don't know enough about this test suite to fully understand what effort that would require.

**Comment by kirbysayshi** [comment]
Awesome! Thank you so much!

**Pull request merged**
